Added apis
Echsecutor/bitcoin_trading.echse pull request #9
Opened 2018-01-29 22:22 UTC by jamidt

2018-02-03 07:24 UTC, jamidt commented
Looks fine.

2018-02-03 17:12 UTC, Echsecutor commented
I have now briefly read the Code, looks very good, thanks!

- would it be possible to write a couple of tests for those APIs not requiring keys?
- maybe BCdeSession should als derive from BaseQuerry?
- do the ShapeshiftTransactions not include any rate? Getting only the amount might not be to interesting. ;)
- the new models are not yet used, are they? E.g. `ShapeshiftMarketinfo` is not instantiated.

2018-02-03 17:13 UTC, Echsecutor commented
this MR adresses the 2. part of https://github.com/Echsecutor/bitcoin_trading.echse/issues/6

2018-02-10 22:34 UTC, Echsecutor requested changes
I have now briefly read the Code, looks very good, thanks!

- would it be possible to write a couple of tests for those APIs not requiring keys?
- maybe BCdeSession should als derive from BaseQuerry?
- do the ShapeshiftTransactions not include any rate? Getting only the amount might not be to interesting. ;)
- the new models are not yet used, are they? E.g. ShapeshiftMarketinfo is not instantiated.

2018-02-13 12:39 UTC, Echsecutor reviewed
> - maybe BCdeSession should als derive from BaseQuerry?
:white_check_mark:

2018-02-13 12:42 UTC, Echsecutor commented on webgui/price_chart/apis.py
> +    def query_json(self, url, *args, **kwargs):
@jamidt  why the `*args, **kwargs` arguments? (unused warning seems ustified)

2018-02-19 22:38 UTC, Echsecutor approved these changes
@jan: Cool, thanks!
I started writing the ETL and adapting the viewers

2018-02-19 22:41 UTC, Echsecutor commented
:white_check_mark: > do the ShapeshiftTransactions not include any rate? Getting only the amount might not be to interesting. 

:white_check_mark: > the new models are not yet used, are they? E.g. ShapeshiftMarketinfo is not instantiated.

2018-02-20 18:22 UTC, merged